#+TITLE: MRK — A file format for marking student work

When judging student performance, it is useful to have both smaller, composable
quantitive judgements, and some qualitative remarks on key areas of interest.
This makes both spreadsheets and mere text-files ill-suited for marking student
work.  Although org-mode can solve this problem to a great extent, it becomes a
heavy tool in the light of having to mark hundreds of students in a distributed
fashion. With org-mode, everything is in one file, while global, intra-student
statistics are not needed until all the students have been fully marked.

* Design Goals

  1. One human-readable/editable file per student.
  2. Export options to spreadsheet-formats.
  3. git-friendly file format.
  4. Synchronization options with Dropbox and/or Google Drive.

Goal 4 is not necessarily related to MRK, but is related to marking student
work with external examiners, who are not always willing to use more explicit
version-control systems, such as git.
