#+TITLE: remark — A DSL for marking student work

#+ATTR_HTML: title="License: BSD 3-Clause"
[[LICENSE][file:https://img.shields.io/badge/License-BSD%203--Clause-blue.svg]]
#+ATTR_HTML: title="Travis CI (Linux + macOS) Status"
[[https://travis-ci.org/oleks/remark][file:https://travis-ci.org/oleks/remark.svg]]
#+ATTR_HTML: title="AppVeyor (Windows) Status"
[[https://ci.appveyor.com/project/oleks/remark][file:https://ci.appveyor.com/api/projects/status/xj8rbfhld9mjrjmg]]

When judging student performance, it is useful to have both small, composable,
quantitive judgements, and qualitative remarks. This makes both spreadsheets
and mere text-files ill-suited for marking student work.  Although
[[http://orgmode.org/][org-mode]] can solve this problem to a great extent, it
becomes a heavy tool in the light of having to mark hundreds of students in a
distributed fashion. With org-mode, everything is in one file, while global,
intra-student statistics are not needed until all the students have been fully
marked.

* Design Goals

  1. One human-readable/editable file per student.
  2. Export options to spreadsheet-formats.
  3. git-friendly file format.
  4. Synchronization options with Dropbox and/or Google Drive.

Goal 4 is not necessarily related to remark, but is related to marking student
work with external examiners, who are not always willing to use more explicit
version-control systems, such as git.

* Syntax

A =.mrk= file is a list of judgements.

A judgement starts with a header mark (a sequence of =#=), a title (followed by
a =:=), given points (followed by =/=), and maximum points (followed by a line
break). The number of =#= determines the /depth/ of the header, and every file
/must/ start at depth 1, but may have multiple depth 1 judgements. Headings may
be arbitrarily nested, but must sum up correctly. For instance, here is a file
containing only quantative remarks:

#+BEGIN_SRC
# Theory: 27/50
## Question 1: 10/10
## Question 2: 10/20
## Question 3: 7/20
# Practice: 35/50
## Task 1: 20/25
## Task 2: 15/25
#+END_SRC

The header of a judgement may be followed by qualitative remarks. Remarks begin
with an indent (two spaces), and a mood mark:

  * =*= for neutral/structural remarks
  * =+= for positive remarks
  * =-= for negative remarks
  * =?= for impartial remarks, where the mood judgement is left to a higher
    authority (e.g., when a teaching assistant is not sure if something is good
    or bad, and would like to let the teacher decide).

Qualitative remarks may be nested arbitrarily.

* Files and Directories

The file-format is kept "git-friendly" by keeping it comprehensible in
plain-text, and allowing for independent marking by splitting the remarks for a
student into multiple files.

The simplest setup is to have one =.mrk= file per student.

To support more exotic setups, =remark= can also work with directories:

If supplied with a directory path, =remark= looks for files ending in =.mrk=
inside that directory, and comprehends the files, as above, in lexicographic
filename order.

Furthermore, if there exists a directory =<basename>= for any =<basename>.mrk=
along the way, =<basename>= is recursively searched for =.mrk= files, and their
contents is appended (in lexicographic filename order) to the last top-level
judgement of =<basename>.mrk=. This allows you to structure your remarks using
directories.

See [[samples][samples]] for some examples of how =.mrk= files may be
structured:

#+BEGIN_SRC
├── basic.mrk
├── directory-with-mrk-files
│   ├── 01-theory.mrk
│   └── 02-practice.mrk
└── mixed-directory
    ├── 01-theory.mrk
    ├── 02-practice
    │   ├── Task1.mrk
    │   └── Task2.mrk
    └── 02-practice.mrk
#+END_SRC

=basic.mrk=, =directory-with-mrk-files=, and =mixed-directory= all yield the
same overall judgements once parsed by =remark=. They merely differ in their
source structure.
